server:
  port: 0

spring:
  application:
    name: employee-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: root


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/





